apiVersion: apps/v1
kind: Deployment
metadata:
  name: "junction-ml"
spec:
  selector:
    matchLabels:
      app: "junction-ml"
  template:
    metadata:
      labels:
        app: "junction-ml"
    spec:
      imagePullSecrets:
        - name: docker-registry-secret-json
      containers:
        - name: "junction-ml"
          image: "ghcr.io/krytoy4yvak/team-13-junction-ml:latest"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: junction-ml-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /ml
        backend:
          service:
            name: junction-ml
            port:
              number: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: "junction-ml"
spec:
  selector:
    app: "junction-ml"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 5000
